package view;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import model.Adocao;
import model.Adotante;
import model.Animal;
import model.EspecieAnimal;
import model.dao.AnimalDAO;
import model.dao.AdotanteDAO;

public class CadastroAdocaoJD extends javax.swing.JDialog {

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    AnimalDAO daoAnimal;
    AdotanteDAO daoAdotante;

    private Adocao adocao;

    /**
     * Creates new form CadastroAdocaoJD
     */
    public CadastroAdocaoJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        daoAnimal = new AnimalDAO();
        daoAdotante = new AdotanteDAO();

        loadEspecies();
        loadAdotantes();
        loadAnimais();

        cmbEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarAnimais(); // Chama o método de filtragem
            }
        });
        filtrarAnimais();

        txtDataAdo.setText(LocalDateTime.now().format(formatter));
    }

    public void loadEspecies() {
        for (EspecieAnimal obj : EspecieAnimal.values()) {
            cmbEspecie.addItem(obj);
        }
    }

    public void loadAdotantes() {
        for (Adotante obj : daoAdotante.listaAdotantes()) {
            cmbAdotante.addItem(obj);
        }
    }

    public void loadAnimais() {
        for (Animal obj : daoAnimal.listaAnimais()) {
            cmbAnimal.addItem(obj);
        }
    }

    private void filtrarAnimais() {
        cmbAnimal.removeAllItems();

        EspecieAnimal especieSelecionada = (EspecieAnimal) cmbEspecie.getSelectedItem();

        if (especieSelecionada != null) {
            List<Animal> animaisDisponiveis = daoAnimal.buscarAnimaisDisponiveisPorEspecie(especieSelecionada);

            for (Animal animal : animaisDisponiveis) {
                cmbAnimal.addItem(animal);
            }
        }

        cmbAnimal.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataAdo = new javax.swing.JTextField();
        cmbAdotante = new javax.swing.JComboBox<>();
        cmbEspecie = new javax.swing.JComboBox<>();
        cmbAnimal = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Adoção");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Data da Adoção:");

        jLabel3.setText("Espécie:");

        jLabel4.setText("Animal:");

        jLabel5.setText("Adotante:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDataAdo)
                                .addComponent(cmbAdotante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 1, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(14, 14, 14)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataAdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdotante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            if (this.adocao == null) {
                this.adocao = new Adocao();
            }

            LocalDate dataAdocao = LocalDate.parse(txtDataAdo.getText(), formatter);

            Animal animalSelecionado;

            boolean isNovoCadastro = (this.adocao.getId() == null || this.adocao.getId() == 0);

            if (isNovoCadastro) {
                animalSelecionado = (Animal) cmbAnimal.getSelectedItem();
                if (animalSelecionado == null) {
                    JOptionPane.showMessageDialog(rootPane, "Selecione um animal para adoção!");
                    return;
                }
                if (!animalSelecionado.isDisponivel()) {
                    JOptionPane.showMessageDialog(rootPane, "Esse animal não está disponível para adoção!");
                    return;
                }
                animalSelecionado.setDisponivel(false);
            } else {
                animalSelecionado = this.adocao.getAnimal();
                if (animalSelecionado == null) {
                    JOptionPane.showMessageDialog(rootPane, "Erro: A adoção não possui um animal associado.");
                    return;
                }
            }
            adocao.setDataAdocao(dataAdocao);
            adocao.setAdotante((Adotante) cmbAdotante.getSelectedItem());
            /*if (animalSelecionado != null && !animalSelecionado.isDisponivel()) {
                JOptionPane.showMessageDialog(rootPane, "Esse animal não está disponível para adoção!");
                return;
            } else {*/
                adocao.setAnimal(animalSelecionado);
                
            //}
            this.dispose();
        } catch (DateTimeParseException e) {
            adocao = null;
            JOptionPane.showMessageDialog(this, "Data inválida. Use o formato: dd-MM-yyyy", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            adocao = null;
            JOptionPane.showMessageDialog(this, "Erro ao registrar adocao: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdocaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroAdocaoJD dialog = new CadastroAdocaoJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Adotante> cmbAdotante;
    private javax.swing.JComboBox<Animal> cmbAnimal;
    private javax.swing.JComboBox<EspecieAnimal> cmbEspecie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDataAdo;
    // End of variables declaration//GEN-END:variables

    public Adocao getAdocao() {
        return this.adocao;
    }

    public void setAdocao(Adocao adocao) {
        this.adocao = adocao;
        txtDataAdo.setText(adocao.getDataAdocao().format(formatter));
        cmbAdotante.setSelectedItem(adocao.getAdotante());
        cmbAnimal.setSelectedItem(adocao.getAnimal());

        if (adocao != null && adocao.getId() != null) {
            cmbAnimal.setEnabled(false);
            cmbEspecie.setEnabled(false);
        } else {
            cmbAnimal.setEnabled(true);
            cmbEspecie.setEnabled(true);
        }
    }
}
